"use client";

import { useRef, useState } from "react";
import { playAudioUrl } from "@/lib/voice-client";

interface AudioPlayerProps {
  audioUrl?: string | null;
  demoMode?: boolean;
  demoMessage?: string;
  loading?: boolean;
  onReplay?: () => void;
  replayLoading?: boolean;
  showElevenLabsBadge?: boolean;
}

export function AudioPlayer({
  audioUrl,
  demoMode = false,
  demoMessage = "Voice generation is running in demo mode.",
  loading = false,
  onReplay,
  replayLoading = false,
  showElevenLabsBadge = true,
}: AudioPlayerProps) {
  const audioRef = useRef<HTMLAudioElement>(null);
  const [playing, setPlaying] = useState(false);

  function togglePlay() {
    const audio = audioRef.current;
    if (!audio || !audioUrl) return;
    if (playing) {
      audio.pause();
      setPlaying(false);
    } else {
      audio.play();
      setPlaying(true);
    }
  }

  if (loading) {
    return (
      <div className="glass-card rounded-xl p-6 animate-pulse">
        <div className="h-4 bg-slate-700/50 rounded w-2/3 mb-3" />
        <div className="h-10 bg-slate-700/50 rounded w-32" />
        <p className="text-sm text-slate-500 mt-3">Generating your personalized voice message…</p>
      </div>
    );
  }

  if (demoMode) {
    return (
      <div className="glass-card rounded-xl p-6 border-amber-500/30">
        <p className="text-sm text-amber-200/90">{demoMessage}</p>
        <p className="text-xs text-slate-500 mt-2">
          Browser voice or text preview is used when ElevenLabs is not configured.
        </p>
        {onReplay && (
          <button
            type="button"
            onClick={onReplay}
            disabled={replayLoading}
            className="mt-4 text-sm text-cyan-400 hover:text-cyan-300"
          >
            {replayLoading ? "Playing…" : "Replay thank-you message"}
          </button>
        )}
      </div>
    );
  }

  if (!audioUrl) return null;

  return (
    <div key={audioUrl} className="glass-card rounded-xl p-6">
      <p className="text-sm text-slate-400 mb-3">Your personalized thank-you message</p>
      <audio
        ref={audioRef}
        src={audioUrl}
        onEnded={() => setPlaying(false)}
        onPause={() => setPlaying(false)}
        className="hidden"
      />
      <div className="flex flex-wrap gap-3 items-center">
        <button
          type="button"
          onClick={togglePlay}
          className="btn-neon rounded-xl px-6 py-2.5 text-sm flex items-center gap-2"
        >
          {playing ? "Pause" : "Play message"}
        </button>
        {onReplay && (
          <button
            type="button"
            onClick={onReplay}
            disabled={replayLoading}
            className="text-sm text-cyan-400 hover:text-cyan-300 disabled:opacity-50"
          >
            Replay
          </button>
        )}
      </div>
      {showElevenLabsBadge && (
        <p className="text-[10px] text-slate-500 mt-3">Generated by ElevenLabs</p>
      )}
    </div>
  );
}

export async function playUrlWithState(
  url: string,
  setPlaying: (v: boolean) => void
): Promise<void> {
  await playAudioUrl(url, {
    onStart: () => setPlaying(true),
    onEnd: () => setPlaying(false),
  });
}
