import Link from "next/link";
import {
  dashboardStats,
  funnelMetrics,
  recentPurchases,
  generatedAudioLog,
} from "@/lib/mock-data";
import { ConversionFunnelViz } from "./ConversionFunnelViz";
import { RevenueChart } from "./RevenueChart";

export function CreatorDashboard() {
  return (
    <div className="max-w-6xl mx-auto px-4 py-12">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 mb-10">
        <div>
          <h1 className="text-3xl font-bold text-gradient">Creator Dashboard</h1>
          <p className="text-slate-400 mt-1">
            Voice commerce analytics · Talk2Buy
          </p>
        </div>
        <Link
          href="/"
          className="text-sm text-cyan-400 hover:text-cyan-300 transition-colors"
        >
          ← Back to storefront
        </Link>
      </div>

      <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4 mb-8">
        <MetricCard
          label="Total revenue"
          value={`¥${dashboardStats.totalRevenue.toLocaleString()}`}
        />
        <MetricCard
          label="Voice conversations"
          value={String(dashboardStats.voiceConversations)}
        />
        <MetricCard
          label="Conversion rate"
          value={`${dashboardStats.conversionRate}%`}
          sub={dashboardStats.conversionDelta}
        />
        <MetricCard
          label="Top recommended"
          value={dashboardStats.topRecommendedProduct}
          small
        />
        <MetricCard label="Total orders" value={String(dashboardStats.totalOrders)} />
        <MetricCard
          label="Voice messages"
          value={String(dashboardStats.voiceMessagesGenerated)}
        />
      </div>

      <div className="glass-card rounded-2xl p-6 mb-8">
        <h2 className="text-lg font-semibold text-slate-100 mb-1">Voice commerce funnel</h2>
        <p className="text-sm text-slate-400 mb-4 italic">
          Voice previews convert passive visitors into confident buyers.
        </p>
        <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-3">
          <MetricCard label="Conversations" value={String(funnelMetrics.voiceConversationsToday)} />
          <MetricCard label="Recommendations" value={String(funnelMetrics.recommendationsGenerated)} />
          <MetricCard label="Preview plays" value={String(funnelMetrics.voicePreviewPlays)} />
          <MetricCard label="Checkout starts" value={String(funnelMetrics.stripeCheckoutStarts)} />
          <MetricCard label="Purchases" value={String(funnelMetrics.purchasesCompleted)} />
          <MetricCard label="Conv. lift" value={funnelMetrics.estimatedConversionLift} />
        </div>
      </div>

      <ConversionFunnelViz />

      <div className="mb-8">
        <RevenueChart />
      </div>

      <div className="grid md:grid-cols-2 gap-6">
        <div className="glass-card rounded-2xl p-6">
          <h2 className="text-lg font-semibold text-slate-100 mb-4">
            Recent purchases
          </h2>
          <ul className="space-y-3">
            {recentPurchases.map((p) => (
              <li
                key={p.id}
                className="flex justify-between items-start text-sm border-b border-slate-700/50 pb-3 last:border-0"
              >
                <div>
                  <p className="text-slate-200">{p.customer}</p>
                  <p className="text-slate-500 text-xs">{p.product}</p>
                </div>
                <div className="text-right">
                  <p className="text-cyan-400">¥{p.amount.toLocaleString()}</p>
                  <p className="text-xs text-slate-600">
                    {new Date(p.date).toLocaleDateString()}
                  </p>
                </div>
              </li>
            ))}
          </ul>
        </div>

        <div className="glass-card rounded-2xl p-6">
          <h2 className="text-lg font-semibold text-slate-100 mb-4">
            Generated voice messages
          </h2>
          <ul className="space-y-3">
            {generatedAudioLog.map((a) => (
              <li
                key={a.id}
                className="text-sm border-b border-slate-700/50 pb-3 last:border-0"
              >
                <p className="text-slate-200">
                  {a.customer} — {a.product}
                </p>
                <p className="text-slate-500 text-xs mt-1 truncate">{a.preview}</p>
                <p className="text-[10px] text-slate-600 mt-1">
                  Generated by ElevenLabs · {new Date(a.createdAt).toLocaleString()}
                </p>
              </li>
            ))}
          </ul>
        </div>
      </div>
    </div>
  );
}

function MetricCard({
  label,
  value,
  sub,
  small,
}: {
  label: string;
  value: string;
  sub?: string;
  small?: boolean;
}) {
  return (
    <div className="glass-card rounded-xl p-4">
      <p className="text-xs text-slate-500 mb-1">{label}</p>
      <p
        className={`font-bold text-slate-100 ${small ? "text-xs leading-snug" : "text-lg"}`}
      >
        {value}
      </p>
      {sub && <p className="text-[10px] text-emerald-400/90 mt-1">{sub}</p>}
    </div>
  );
}
