"use client";

import { useState } from "react";
import { getProductById, formatPrice } from "@/lib/products";
import { playVoiceText } from "@/lib/voice-client";
import { CheckoutButton } from "./CheckoutButton";
import { useToast } from "./Toast";
import type { VoiceOrbState } from "@/types";

interface RecommendationCardProps {
  productId: string;
  whyItFits?: string;
  whatYouGet?: string;
  cta?: string;
  onVoiceStateChange?: (state: VoiceOrbState) => void;
}

export function RecommendationCard({
  productId,
  whyItFits,
  whatYouGet,
  cta,
  onVoiceStateChange,
}: RecommendationCardProps) {
  const product = getProductById(productId);
  const [sampleLoading, setSampleLoading] = useState(false);
  const { showToast } = useToast();

  if (!product) return null;

  async function handleHearSample() {
    setSampleLoading(true);
    onVoiceStateChange?.("speaking");
    try {
      const result = await playVoiceText(product!.sampleScript, {
        onStart: () => onVoiceStateChange?.("speaking"),
        onEnd: () => onVoiceStateChange?.("idle"),
      });
      if (result.demo && result.usedBrowserFallback) {
        showToast("Demo mode: playing sample with browser voice", "info");
      } else if (result.demo) {
        showToast(result.message ?? "Demo mode: voice preview", "info");
      }
    } finally {
      setSampleLoading(false);
      onVoiceStateChange?.("idle");
    }
  }

  return (
    <div className="mx-4 mb-4 glass-card rounded-2xl p-5 border-violet-500/20">
      <p className="text-xs font-semibold uppercase tracking-wider text-violet-400 mb-3">
        AI Recommended for You
      </p>
      <h3 className="text-lg font-bold text-slate-100">{product.name}</h3>
      <p className="text-cyan-400 font-semibold mt-1">
        {formatPrice(product.price, product.currency)}
      </p>
      <p className="text-sm text-slate-300 mt-2">{product.shortBenefit}</p>
      {whyItFits && (
        <p className="text-sm text-slate-400 mt-3">
          <span className="text-slate-300 font-medium">Why it fits: </span>
          {whyItFits}
        </p>
      )}
      {whatYouGet && (
        <p className="text-sm text-slate-400 mt-2">
          <span className="text-slate-300 font-medium">What you get: </span>
          {whatYouGet}
        </p>
      )}
      {cta && <p className="text-sm text-cyan-300/90 mt-3 font-medium">{cta}</p>}
      <div className="flex flex-wrap gap-3 mt-5">
        <CheckoutButton productId={productId} label="Buy with Stripe" showStripeBadge />
        <button
          type="button"
          onClick={handleHearSample}
          disabled={sampleLoading}
          className="rounded-xl px-4 py-2 text-sm border border-cyan-500/40 text-cyan-300 hover:bg-cyan-500/10 transition-colors disabled:opacity-50"
        >
          {sampleLoading ? "Generating…" : "Hear sample"}
        </button>
      </div>
      <p className="text-[10px] text-slate-500 mt-3">Generated by ElevenLabs</p>
    </div>
  );
}
